# Generated by Django 3.1.6 on 2026-05-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
