# Generated by Django 3.1.6 on 2026-05-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
