# Generated by Django 3.1.6 on 2026-05-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('participants', models.IntegerField(default=0)),
            ],
        ),
    ]
